
@extends('admin.layout')

@section('title') Add new Payment @stop

@section('main')

<main class="column is-12-desktop is-12-mobile padding-top-10 padding-bottom-20 columns is-multiline" >

    <!--Generated by Functions-->
    <section class="column is-12 padding-0">{!! breadcrumb('Payments') !!}</section>
    
    <section class="column is-12 padding-0 margin-bottom-20">

        <h1 class="title is-3">Add new payment</h1>

    </section>

    <section class="column is-12 padding-0">{!! errors($errors) !!}</section>

    <section class="column is-12 padding-0">

    {!! Form::open( ['url'=> action('Payments@store'), 'enctype'=>'multipart/form-data', 'class'=> 'columns is-multiline' ]) !!}

        
        <div class="field has-addons column is-6-desktop is-12-mobile">
            <div class="control">
                <a class="button is-info">
                Name
                </a>
            </div>
            <div class="control is-expanded">
                {!! Form::text('name', old('name') , ['class'=>'input', 'aria-describedby'=> 'name']) !!}
            </div>
        </div>
                
                
        <div class="field has-addons column is-6-desktop is-12-mobile">
            <div class="control">
                <a class="button is-info">
                Due date
                </a>
            </div>
            <div class="control is-expanded">
                {!! Form::text('due_date', old('due_date') , ['class'=>'input datepicker', 'aria-describedby'=> 'due_date']) !!}
            </div>
        </div>
                
                
                
        <div class="field has-addons column is-6-desktop is-12-mobile">
            <div class="control">
                <a class="button is-info">
                Payment date
                </a>
            </div>
            <div class="control is-expanded">
                {!! Form::text('payment_date', old('payment_date') , ['class'=>'input datepicker', 'aria-describedby'=> 'payment_date']) !!}
            </div>
        </div>
                
                
        <div class="field has-addons column is-6-desktop is-12-mobile">
            <div class="control">
                <button type="button" class="button is-info">Paid?</button>
            </div>
            <div class="control is-expanded">
                <div class="select is-fullwidth">
                    {!! Form::select('is_paid', [ ''=>'-Select-','1'=>'Yes', '0'=>'No'], old('is_paid')) !!}
                </div>
            </div>
        </div>
        
                
        <div class="field column is-12">
            <div class="control">
                <a class="button is-info">
                Payment details
                </a>
            </div>
            <div class="control is-expanded">
                {!! Form::textarea('payment_details', old('payment_details') , ['class'=>'textarea summernote']) !!}
            </div>
        </div>
                
        <div class="field has-addons column is-6-desktop is-12-mobile">
            <div class="control">
                <a class="button is-info">
                Attachment file
                </a>
            </div>
            <div class="control is-expanded">
                {!! Form::file('attachment_files', ['class'=>'file']) !!}
            </div>
        </div>
        
                
        <div class="field is-horizontal column is-12">
            <div class="field-body">
                <div class="field">
                    <div class="control has-text-centered">
                        <button class="button is-info" type="submit">Save</button>
                    </div>
                </div>
            </div>
        </div>
    
    {!! Form::close() !!}


    </section>
</main>
@stop
        