@extends('admin.layout')

@section('title')Payment - {{ settings()->application_name }} @stop

@section('main')

<main class="column is-12-desktop is-12-mobile padding-top-10 padding-bottom-20 columns is-multiline" >

    
    <!--Generated by Functions-->
    <section class="column is-12 padding-0">{!! breadcrumb('Payments') !!}</section>
    
    <section class="column is-12 padding-0">

        <h1 class="title is-3">Payment</h1>

    </section>


    <section class="column is-12 padding-0">{!! errors($errors) !!}</section>
    
    <section class="column is-12 padding-0 has-text-right blue-text">
        
        <a href="{{action('Payments@edit', $payment->id)}}" class="is-link">Edit payment</a>
    
    </section>
        
    @if( $payment )
    <section class="column is-12 padding-0">
        <table class="table table-bordered table-striped">
            <tdead>
                <tr>
                    <td width="200" class="font-weight-700">Title</td>
                    <td class="font-weight-700">Details</td>
                </tr>
            </tdead>
            <tbody>
                    <tr>
                        <td>Id</td>
                        <td>{{ $payment->id }}</td>
                    </tr>
                    
                    <tr>
                        <td>Name</td>
                        <td>{{ $payment->name }}</td>
                    </tr>
                    
                    <tr>
                        <td>Due date</td>
                        <td>{{ $payment->due_date }}</td>
                    </tr>
                    
                    <tr>
                        <td>Payment date</td>
                        <td>{{ $payment->payment_date }}</td>
                    </tr>
                    
                    <tr>
                        <td>Is paid</td>
                        <td>{{ $payment->is_paid }}</td>
                    </tr>
                    
                    <tr>
                        <td>Payment details</td>
                        <td>{{ $payment->payment_details }}</td>
                    </tr>
                    
                    <tr>
                        <td>Attachment file</td>
                        <td>
                            @if( strlen( $payment->attachment_file ) > 5 )
                            <a href="{{ $payment->attachment_file }}" class="btn btn-default btn-rounded btn-xs"><span class="fa fa-download"></span></a>
                            @else
                            None
                            @endif
                        </td>
                    </tr>
                    
                    <tr>
                        <td>Created at</td>
                        <td>{{ $payment->created_at }}</td>
                    </tr>
                    
                    <tr>
                        <td>Updated at</td>
                        <td>{{ $payment->updated_at }}</td>
                    </tr>
                    
                <tr>
                    <td>
                        {!! edits('Payments', $payment->id, 'edit', ['class'=>'button is-warning is-small']) !!}
                                
                    </td>
                    <td>
                        {!! deletes('Payments', $payment->id, '<span class=\'fa fa-times\'></span>', ['class'=>'button is-danger is-small']) !!}
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
    @endif
        </main>

@stop